### ISSUE TITLE
Déplacer le service vers signup.api.gouv.fr

### ISSUE THREAD

**Issue by Flightan** [betagouv/api-particulier-courtier-front#102]
- Remplacer le logo particulier.api.gouv.fr en api.gouv.fr
 - changer ovh et settings sur github pages
 - supprimer la page d'accueil - quand on clique sur le logo on retourne sur api.gouv.fr ou sur api.gouv.fr/api-particulier (a definir)
 - renommer /contractualisation en /api-particulier

**Comment by annemarie35** [comment]
- Ajouter sur chaque formulaire un champ invisible qui renseigne le type de formulaire dans ènrollment : 
`resource_provider_type`existe déjà côté back mais pas dans `enrollment`

- Quand je suis sur la page des demandes et que je clique sur voir, je dois pouvoir être redirigé·e vers le formulaire api-particulier ou le formulaire dgfip. Actuellement, c'est seulement le dgfip.

-> voir si je ne crée pas une nouvelle issue
