### ISSUE TITLE
Modifier le formulaire api-particulier existant

### ISSUE THREAD

**Issue by Flightan** [betagouv/api-particulier-courtier-front#105]
# Introduction
>Pour avoir accès à l'API Particulier, diffusant des données personnelles, vous devez obtenir un agrément. 
>L'accès à cette API n'est pour l'instant disponible que si vous êtes:
> - une administration
> - une entreprise prestataire d'une administration ou ayant une délégation de service public 
> 
> Vous devez justifier d’une simplification pour les citoyens, et vous engager à n’accéder aux données personnelles qu’avec l’accord explicite de l’usager.

# Identité
Champs SIRET -> cherche les données sur l'API SIRENE, stocke:
 - raison sociale
 - adresse
 - responsable
 - code NAF

Les champs contacts sont de deux types: Obligatoires ou non.
## Contacts obligatoires (nom et email)
 - Responsable de traitement 
 - DPO
 - Technique
 - Métier
 - Autre (0 .. *)

# Démarche
Intitulé

Finalité
>C'est la raison pour laquelle vous collectez des données personnelles, l'objectif qui est poursuivi par le fichier que vous mettez en place. Par exemple, « télé-procédure permettant aux usagers de demander une aide au paiement de la cantine des collégiens » ou « télé-procédure de demande de bourses de lycée ».

## Cadre juridique

Indiquez la référence ou l'URL du texte.

# Données

- Bloc scopes
- Durée de conservation des données
- Destinataires
 > Pour mémoire, seuls les agents dûment habilités pour traiter une démarches doivent accéder aux données transmises.

- Bloc TL;DR convention 
<img width="700" alt="screen shot 2018-04-16 at 11 38 50" src="https://user-images.githubusercontent.com/1475946/38801676-c93478a8-416a-11e8-829b-5b13b73462f4.png">

- Checkbox
`J'ai compris et j'accepte <a href="convention.pdf">la convention d’adhésion à API Particulier</a>`

- Checkbox
`Je confirme que le DPO de mon organisme est informé de la présente demande`

![schema](https://user-images.githubusercontent.com/1475946/38800729-4cd0870e-4168-11e8-875e-ac257f6bd3ce.jpg)

**Comment by annemarie35** [comment]
@Flightan @pknoth 
Je rajoute que quand on clique sur le bouton submit, ça envoie un mail aux personnes renseignées.

**Comment by Flightan** [comment]
@annemarie35 Je propose qu'on garde la gestion des comptes telle quelle actuellement et qu'on la modifie dans une prochaine version.
