### ISSUE TITLE
Ajouter une page contractualisation

### ISSUE THREAD

**Issue by annemarie35** [betagouv/api-particulier-courtier-front#20]
- un lien vers une page /contractualisation dans le header 
- des sections numérotées et un menu d’accès rapide (cf https://partenaires.franceconnect.gouv.fr/monprojet/decouverte)

**Comment by annemarie35** [comment]
J'avais créé cette issue, voir si ça rejoint pas la story login

**Comment by Flightan** [comment]
## Introduction

```
Pour pouvoir bénéficier du raccordement, le cadre légal et réglementaire des fournisseurs de
service (mairie, crèche, …) doit permettre la transmission des données dématérialisées à votre entité administrative.
 
Il vous est donc demandé de préciser les références du fondement légal de votre droit à demander ces données
(délibération du conseil municipal, décret …) ainsi que les informations relatives à votre téléservice.
```

`Décrivez brièvement votre service ainsi que l'utilisation prévue des données transmises: <textarea>`

`Veuillez transmettre le fondement juridique sur lequel s'appuie votre demande: <textarea>`

## Choix des jeux de données

```
La loi informatique et libertés définit les principes à respecter lors de la collecte, du traitement et de la conservation de données personnelles.
L'article 6 précise :
  3° [les données] sont adéquates, pertinentes et non excessives au regard des finalités pour lesquelles
    elles sont collectées et de leurs traitements ultérieurs ;
  4° Elles sont exactes, complètes et, si nécessaire, mises à jour ; les mesures appropriées doivent être
    prises pour que les données inexactes ou incomplètes au regard des finalités pour lesquelles elles sont
    collectées ou traitées soient effacées ou rectifiées ;

Nous vous remercions de sélectionner uniquement les données strictement nécessaires à votre téléservice.
Le non-respect du principe de proportionnalité vous expose vis à vis de la CNIL.
```

`<checkboxes jeux de données>`

## Volumétrie

```
Connaitre les données relatifs à la volumétrie et à la saisonnalité de votre téléservice nous permettra de vous
offrir la meilleure qualité de service possible. En effet, cela permettra de prévenir les pics de charges et de
transmettre ces informations aux fournisseurs de vos données.

Conformément à notre charte, nous nous réservons le droit de réduire ou couper les appels autorisés au fournisseur de service.
```


`Connaissez-vous le volume global annuel des demandes de votre téléservice ? <input>`

`Connaissez-vous le pic de charge (en nombre de demandes horaires) ? <input>`

`Connaissez-vous la répartition de la charge des demandes mensuelles (0 si le service est fermé) ?
<12 inputs, 1 par mois>`

## Homologation de sécurité

```
Le Référentiel Général de Sécurité (RGS 2.0) rend la démarche d’homologation obligatoire pour les SI relatifs aux échanges
entre une autorité administrative et les usagers ou entre autorités administratives.

Si vous l'avez déjà fait, complétez les informations relatives à l'homologation et déposez la décision formelle d’homologation
(également appelée attestation formelle).

Si vous ne l'avez pas encore fait, envoyez-nous tout de même votre demande et nous vous aiderons à entamer cette démarche.
```

`<inputs homologation>`
`<uploader document>`

## Obligations CNIL

```
L'entrée en vigueur le 25 mai 2018 du règlement européen sur la protection des données supprime totalement le régime déclaratif.
Les fournisseurs de services ont en particulier l'obligation de tenir un registre de leurs activités de traitement, d'encadrer
les opérations sous-traitées dans les contrats de prestation de services, de formaliser des politiques de confidentialité des
données et des procédures relatives à la gestion des demandes d’exercice des droits.

La désignation d’un délégué à la protection des données - successeur du correspondant informatique et libertés (CIL) dont la désignation
est aujourd’hui facultative - devient obligatoire pour les organismes et autorités publics, et donc pour les fournisseurs de services.
```

`Délégué·e à la protection de données: <input texte>`

## Convention

```
Merci de prendre connaissance de la convention d'adhésion d'API Particulier afin de demander un jeton d'accès en décrivant votre projet. 
Un résumé est fait ci-dessous. Néamoins, il ne se substitue pas à la lecture de la convention d'adhésion.
```

Vous pouvez :
- Récupérer les données nécessaires à vos démarches
  - Vous récupérez des données fiables que vous pouvez facilement intégrer dans vos procesus d'instruction.
- Afficher des données à l’usager
  - Il est possible d'afficher des données à l’usager si elles ne menacent pas sa vie privée. Par exemple, les tarifs de la cantine après avoir été calculés à partir du quotient familial récupéré auprès de la CAF.

Vous devez :
- Accepter la charte
  - Cette charte vous donne droit à un jeton d'accès à l'API Particulier pour récupérer des données fiables utiles à vos démarches.
- Traiter la bonne donnée par le bon agent de la collectivité
  - L'agent habilité du service instructeur peut accéder aux données personnelles.
- Informer correctement l’usager
  - Explicitement demander l'accord de l'usager pour récupérer ses données auprès d'un fournisseur.

Vous ne pouvez pas :
- Afficher des données confidentielles à l’usager
  - L’usager n’étant pas authentifié, aucune garantie ne vous permet d’afficher des données brutes récupérées auprès de l'API sans prendre le risque de les dévoiler à un tiers.
- Recupérer les informations par lot
  - L’API Particulier propose du point à point, vous ne pouvez lancer des récupérations de données en masse.

`<lien vers notre charte>`


`<grosse checkbox importante>J'accepte et affirme avoir dit la vérité vraie.`
`<gros bouton important>Envoyer ma demande`

**Comment by Flightan** [comment]
Il va falloir pouvoir stocker des documents, je propose de le faire en mock dans cette PR et d'en rediscuter.
