### ISSUE TITLE
Css > custom CSS file ou jsx dans les components

### ISSUE THREAD

**Issue by annemarie35** [betagouv/api-particulier-courtier-front#34]
Est-ce qu'on continue d'utiliser des fichiers CSS (template.css et custom.css) ou bien est-ce que l'on déporte le CSS dans du CSS inline.

**Comment by pknoth** [comment]
c'est un ticket ou une question sur un choix technique ?

**Comment by Flightan** [comment]
On reste avec les fichiers CSS pour l'instant.
