### ISSUE TITLE
V2 bootstrap (react/next)

### ISSUE THREAD

**Issue by annemarie35** [betagouv/api-particulier-courtier-front#6]
Cette version doit pouvoir cohabiter avec l'existant qui deviendra la V1.
Cette version sera sur une branche V2.

Créer un environnement de développement sur le cloud (peut-être cloudwatt)

**Comment by annemarie35** [comment]
Premiers commit -> projet angular remplacé par une première passe en react next

**Comment by pknoth** [comment]
pousser le tout sur une branche V2
