### ISSUE TITLE
Ajouter un script de déploiement pour github pages

### ISSUE THREAD

**Issue by annemarie35** [betagouv/api-particulier-courtier-front#7]
Regarder ce qui a été fait sur https://github.com/betagouv/open-academie/blob/master/deploy.sh

Pour le moment cela peut-être déployé sur github pages

--> Ne pas oublier de mettre à jour le readme

**Comment by pknoth** [comment]
On pourrait l'héberger sur cloudwatt, la sandbox du courtier V1 est déployé sur cette infra (voir api-particulier-courtier-ansible sur gitlab)
